name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /www/wwwroot/nfcglobaltech.uz/nfc-fr
            printf "${{ secrets.PASSWORD }}\n" | sudo -S git pull
            
